cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('checkout/confirmation/<str:order_number>/', views.order_confirmation, name='order_confirmation'),
    path('cache_checkout_data/', views.cache_checkout_data, name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),
]

fine_furnishings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profiles/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('products/', include('products.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

checkout/forms.py
from django import forms
from .models import Order
from profiles.models import UserAddress, UserProfile

# Define country choices with only Ireland ("IE")
COUNTRY_CHOICES = [
    ('IE', 'Ireland'),
]

class OrderForm(forms.ModelForm):
    """ 
    A form to allow the user to fill out their details during checkout
    """
    full_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=100, required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    street_address1 = forms.CharField(max_length=255, required=True)
    street_address2 = forms.CharField(max_length=255, required=False)
    town_or_city = forms.CharField(max_length=100, required=True)
    county = forms.CharField(max_length=100, required=True)
    postcode = forms.CharField(max_length=20, required=True)
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, required=True, widget=forms.Select(attrs={'readonly': 'readonly'}))
    address_choices = forms.ChoiceField(choices=[], required=False)
    address_name = forms.CharField(max_length=50, required=False)
    
    class Meta:
        model = Order
        fields = (
            'full_name',
            'email',
            'phone_number',
            'address_choices',
            'address_name',
            'street_address1',
            'street_address2',
            'town_or_city',
            'county',
            'postcode',
            'country',
        )

    def __init__(self, user_profile=None, *args, **kwargs):
        selected_address = kwargs.pop('selected_address', None)
        super().__init__(*args, **kwargs)

        if user_profile:
            user = user_profile.user_id
            self.fields['full_name'].initial = f"{user.first_name} {user.last_name}"
            self.fields['email'].initial = user.email
            self.fields['phone_number'].initial = user_profile.phone

            address_choices = [(address.id, address.address_name) for address in UserAddress.objects.filter(user_profile=user_profile)]
            self.fields['address_choices'].choices = [('', 'Select an address')] + address_choices
            
            if selected_address:
                address = UserAddress.objects.get(id=selected_address)
                self.fields['street_address1'].initial = address.street_address_1
                self.fields['street_address2'].initial = address.street_address_2
                self.fields['town_or_city'].initial = address.town_city
                self.fields['county'].initial = address.county
                self.fields['postcode'].initial = address.post_code
                self.fields['country'].initial = 'IE'
                self.fields['country'].widget.attrs['disabled'] = True

        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'address_name': 'Address Name',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'town_or_city': 'Town or City',
            'county': 'County',
            'postcode': 'Postal Code',
            'country': 'Country',
        }

        for field in self.fields:
            if field != 'address_choices':
                self.fields[field].widget.attrs['placeholder'] = placeholders[field]
                self.fields[field].widget.attrs['class'] = 'stripe-style-input'
                self.fields[field].label = False
    
    def save(self, commit=True):
        """
        Override the save method to include user details in the Order model.
        """
        order = super().save(commit=False)
        order.user_name = self.cleaned_data['full_name']
        order.user_email = self.cleaned_data['email']
        order.user_phone = self.cleaned_data['phone_number']

        if commit:
            order.save()
            
            # Handle address
            address_id = self.cleaned_data.get('address_choices')
            if address_id:
                try:
                    address = UserAddress.objects.get(id=address_id)
                    order.address = address
                except UserAddress.DoesNotExist:
                    pass
            else:
                # Update address with the form data
                address_name = self.cleaned_data['address_name']
                address_data = {
                    'street_address_1': self.cleaned_data['street_address1'],
                    'street_address_2': self.cleaned_data['street_address2'],
                    'town_city': self.cleaned_data['town_or_city'],
                    'county': self.cleaned_data['county'],
                    'post_code': self.cleaned_data['postcode'],
                    'country': self.cleaned_data['country'],
                }
                user_address, created = UserAddress.objects.update_or_create(
                    user_profile=order.user_profile,
                    address_name=address_name,
                    defaults=address_data,
                )
                order.address = user_address
            
            order.save()
        return order

checkout/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import JsonResponse

from .forms import OrderForm
from .models import Order, OrderItems
from profiles.models import UserProfile, UserAddress
from products.models import Product
from cart.contexts import cart_contents

import stripe
import json

@require_POST
def cache_checkout_data(request):
    """
    View to get meta data if user chooses to 'save info'.
    Implemented with the Boutiqe Ado Walkthrough - Stripe Part 13
    """
    try:
        pid = request.POST.get('client_secret').split('_secret')[0]
        stripe.api_key = settings.STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(pid, metadata={
            'cart': json.dumps(request.session.get('cart', {})),
            'save_info': request.POST.get('save_info'),
            'username': request.user,
        })
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(request, 'Sorry, your payment cannot be \
            processed right now. Please try again later.')
        return HttpResponse(content=e, status=400)


@login_required
def checkout(request):
    """ 
    A view to handle the checkout process using Stripe payments
    """
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    intent = None
    user_profile = request.user.userprofile  # Assuming user is logged in and has a profile

    cart = request.session.get('cart', {})
    user_addresses = []

    if request.method == 'POST':
        form = OrderForm(data=request.POST, user_profile=user_profile)
        if form.is_valid():
            pid = request.POST.get('client_secret').split('_secret')[0]
            # Check if an order with the same stripe_pid already exists
            existing_order = Order.objects.filter(stripe_pid=pid).first()
            if existing_order:
                messages.error(request, 'This order has already been processed.')
                return redirect(reverse('order_confirmation', args=[existing_order.order_number]))

            # Create order but don't save until payment is confirmed
            order = form.save(commit=False)
            order.user_profile = user_profile

            # Set user details
            order.user_name = form.cleaned_data.get('full_name')
            order.user_email = form.cleaned_data.get('email')
            order.user_phone = form.cleaned_data.get('phone_number')

            order.delivery_charge = 30
            order.stripe_pid = pid
            order.original_cart = json.dumps(cart)

            # Handle address
            address_id = form.cleaned_data.get('address_choices')
            if address_id:
                try:
                    address = UserAddress.objects.get(id=address_id)
                    order.address = address
                except UserAddress.DoesNotExist:
                    messages.error(request, 'Selected address does not exist.')
                    return redirect(reverse('checkout'))
            else:
                address_name = form.cleaned_data.get('address_name')
                address_data = {
                    'street_address_1': form.cleaned_data['street_address1'],
                    'street_address_2': form.cleaned_data['street_address2'],
                    'town_city': form.cleaned_data['town_or_city'],
                    'county': form.cleaned_data['county'],
                    'post_code': form.cleaned_data['postcode'],
                    'country': form.cleaned_data['country'] or 'IE',
                }

                user_address, created = UserAddress.objects.update_or_create(
                    user_profile=user_profile,
                    address_name=address_name,
                    defaults=address_data,
                )
                order.address = user_address

            try:
                # Save the order after the address is confirmed
                order.save()

                # Create order items
                for item_id, product_data in cart.items():
                    try:
                        product = Product.objects.get(id=item_id)
                        if isinstance(product_data, int):
                            order_item = OrderItems(
                                order=order,
                                product=product,
                                quantity=product_data,
                            )
                            order_item.save()
                        else:
                            for size, quantity in product_data['bedframes_by_size'].items():
                                order_item = OrderItems(
                                    order=order,
                                    product=product,
                                    quantity=quantity,
                                    bedframe_size=size,
                                )
                                order_item.save()

                    except Product.DoesNotExist:
                        messages.error(request, (
                            "One of the products in your shopping cart wasn't found in our database. "
                            "Please contact us for assistance!")
                        )
                        order.delete()
                        return redirect(reverse('cart'))

                # Clear cart after successful order processing
                if 'cart' in request.session:
                    del request.session['cart']

                request.session['save_info'] = 'save-info' in request.POST
                return redirect(reverse('order_confirmation', args=[order.order_number]))

            except Product.DoesNotExist:
                messages.error(request, (
                    "One of the products in your shopping cart wasn't found in our database. "
                    "Please contact us for assistance!")
                )
                order.delete()
                return redirect(reverse('cart'))
        else:
            messages.error(request, 'There was an error with your order. Please double check your information.')

    # Check if the cart is empty
    cart = request.session.get('cart', {})
    if not cart:
        messages.error(request, 'Your cart is empty!')
        return redirect(reverse('products'))

    current_cart = cart_contents(request)
    total = current_cart['order_total']
    stripe_total = round(total * 100)
    stripe.api_key = stripe_secret_key
    intent = stripe.PaymentIntent.create(
        amount=stripe_total,
        currency=settings.STRIPE_CURRENCY,
    )

    initial_data = {
        'full_name': request.user.get_full_name(),
        'email': request.user.email,
        'phone_number': user_profile.phone,
    }

    user_addresses = UserAddress.objects.filter(user_profile=user_profile)
    if user_addresses.exists():
        user_address = user_addresses.first()
        initial_data.update({
            'street_address1': user_address.street_address_1,
            'street_address2': user_address.street_address_2,
            'town_or_city': user_address.town_city,
            'county': user_address.county,
            'postcode': user_address.post_code,
            'country': user_address.country,
        })
    form = OrderForm(initial=initial_data, user_profile=user_profile)

    if not stripe_public_key:
        messages.warning(request, 'Stripe public key is missing. Did you forget to set it in your environment?')

    template = 'checkout/checkout.html'
    context = {
        'user_addresses': user_addresses,
        'order_form': form,
        'stripe_public_key': stripe_public_key,
        'client_secret': intent.client_secret if intent else '',
    }

    return render(request, template, context)


def order_confirmation(request, order_number):
    """
    View to handle successful order checkouts
    """
    save_info = request.session.get('save_info')
    order = get_object_or_404(Order, order_number=order_number)
    email = order.user_profile.user_id.email
    user_profile = order.user_profile
    address = order.address

    messages.success(request, f'Order successfully processed! Your order number is {order_number}.')

    if 'cart' in request.session:
        del request.session['cart']

    template = 'checkout/order_confirmation.html'
    context = {
        'order': order,
        'order_number': order_number,
        'email': email,
        'address': address,
    }
    return render(request, template, context)

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load cart_tools %}

{% block meta_description %}Complete your furniture purchase effortlessly with our efficient checkout page at Fine Furnishings. Experience a smooth and secure payment process.{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block search_bar %}
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
    {% if not user.is_authenticated %}
        <script type="text/javascript">
            window.location.href =
            "{% url 'account_login' %}?next={% url 'checkout' %}";
        </script>
    {% else %}
        <div class="container text-white mb-3">
            <div class="row justify-content-center mt-md-3">
                <div class="col-md-8 col-sm-12 text-center">
                    <h1 class="text-center text-white wishlist-text">Secure Checkout</h1>
                    <div class="d-flex justify-content-center mt-md-3 mb-4">
                        <button type="submit" class="btn btn-secondary btn-md">
                            <a href="{% url 'products' %}" class="dropdown-item">Continue Shopping</a>
                        </button>
                    </div>
                </div>
            </div>
            <div class=
            "col-12 text-center order-lg-last mb-5 text-white">
                <p class="text-white faq-text order-summary-text">
                Order Summary ({{ product_count }})
                </p>
                <div class="row">
                    <div class="col-7 offset-2">
                        <p class="mb-1 mt-0 small text-white">Item</p>
                    </div>
                    <div class="col-3 text-right">
                        <p class="mb-1 mt-0 small text-white">Subtotal</p>
                    </div>
                </div>
                {% for item in cart_items %}
                    <div class="row">
                        <div class="col-2 mb-1">
                            <a href=
                            "{% url 'product_detail' item.product.id %}">
                                {% if item.product.image %}
                                    <img class="img-fluid rounded"
                                    src="{{ item.product.image.url }}"
                                    alt="{{ product.name }}">
                                {% else %}
                                    <img class="img-fluid rounded"
                                    src=
                                    "{% static 'images/coming-soon-placeholder-image.png' %}"
                                    alt="{{ product.name }}">
                                {% endif %}
                            </a>
                        </div>
                        <div class="col-7">
                            <p class="my-0 mb-1">
                            <strong>{{ item.product.name }}</strong>
                            </p>
                            <p class="my-0 small">
                            Size: {% if item.product.bedframe_sizes %}
                            {{ item.size|upper }}{% else %}N/A{% endif %}
                            </p>
                            <p class="my-0 small text-white mb-3">
                            Qty: {{ item.quantity }}
                            </p>
                        </div>
                        <div class="col-3 text-right">
                            <p class="my-0 small text-white">
                            €{{ item.product.price | calc_subtotal:item.quantity }}
                            </p>
                        </div>
                    </div>
                {% endfor %}
                <hr class="my-0">
                <div class="row text-white text-right">
                    <div class="col-7 offset-2">
                        <p class="my-0">Product Total:</p>
                        <p class="my-0">Delivery:</p>
                        <p class="my-0">Order Total:</p>
                    </div>
                    <div class="col-3">
                        <p class="my-0">€{{ total | floatformat:2 }}</p>
                        <p class="my-0">€{{ delivery | floatformat:2 }}</p>
                        <p class="my-0">
                        <strong>
                        €{{ order_total | floatformat:2 }}
                        </strong>
                        </p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-12 mb-5 text-white">
                    <p class="faq-text">
                    Please fill out the form below to complete your order.
                    </p>
                    <form action="{% url 'checkout' %}" method="POST"
                    id="payment-form">
                        {% csrf_token %}
                        <fieldset class="px-3 mb-3 text-white">
                            <legend
                            class=
                            "fieldset-label faq-text text-white px-2 w-auto">
                            Details
                            </legend>
                            {{ order_form.full_name | as_crispy_field }}
                            {{ order_form.email | as_crispy_field }}
                        </fieldset>
                        <fieldset class="px-3 mb-5 text-white">
                            <legend
                            class=
                            "fieldset-label faq-text text-white px-2 w-auto">
                            Delivery
                            </legend>
                            {{ order_form.phone_number | as_crispy_field }}
                            <select id="id_address_choices" name="address_choices">
                                <option value="">Select an address</option>
                                {% for address in user_addresses %}
                                    <option value="{{ address.id }}">
                                        {{ address.street_address_1 }}, {{ address.town_city }}, {{ address.post_code }}
                                    </option>
                                {% empty %}
                                    <option value="">No addresses available</option>
                                {% endfor %}
                            </select>
                            {{ order_form.street_address1 | as_crispy_field }}
                            {{ order_form.street_address2 | as_crispy_field }}
                            {{ order_form.town_or_city | as_crispy_field }}
                            {{ order_form.county | as_crispy_field }}
                            {{ order_form.postcode | as_crispy_field }}
                            {{ order_form.country | as_crispy_field }}
                            <div
                            class=
                            "form-check form-check-inline float-right mr-0">
                                <label class="form-check-label"
                                for="id-save-info">
                                Save this delivery information to my profile
                                </label>
                                <input class="form-check-input ml-2 mr-0"
                                type="checkbox" id="id-save-info"
                                name="save-info" checked>
                            </div>
                        </fieldset>
                        <fieldset class="px-3 text-white">
                            <legend
                            class=
                            "fieldset-label faq-text text-white px-2 w-auto mb-0 payment-text">
                            Payment
                            </legend>
                            <hr class="hr-color">
                            <!-- A Stripe card element will go here -->
                            <div class="form-group mb-3">
                                <div class="mb-3" id="card-element"></div>
                                <!-- Used to display form errors -->
                                <div class="mb-3 text-danger"
                                id="card-errors" role="alert">
                                </div>
                                <!-- Pass the client secret to the view so we can get the payment intent id -->
                                <input type="hidden" value="{{ client_secret }}"
                                name="client_secret">
                            </div>
                            <hr class="hr-color">
                        </fieldset>

                        <div class="submit-button text-right mt-5 mb-2">
                            <a href="{% url 'cart' %}"
                            class="btn btn-outline-light rounded-2">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="font-weight-bold">
                                Update Cart
                                </span>
                            </a>
                            <button id="submit-button"
                            class="btn btn-light rounded-2">
                                <span class="font-weight-bold">
                                Complete Order
                                </span>
                                <span class="icon">
                                    <i class="fas fa-lock"></i>
                                </span>
                            </button>
                            <p class="small text-warning my-0 mt-3 payment-text">
                                <span class="icon">
                                    <i class="fas fa-exclamation-circle"></i>
                                </span>
                                <span>Your card will be charged
                                <strong>
                                €{{ order_total|floatformat:2 }}
                                </strong>
                                </span>
                            </p>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>        
    {% endif %}
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    {{ stripe_public_key|json_script:"id_stripe_public_key" }}
    {{ client_secret|json_script:"id_client_secret" }}
    <script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Declare an empty array to hold address data
            let addresses = [];

            // Loop through user's saved addresses to populate the array
            {% for address in user_addresses %}
                addresses.push({
                    id: "{{ address.id }}",
                    street_address1: "{{ address.street_address_1 }}",
                    street_address2: "{{ address.street_address_2 }}",
                    town_or_city: "{{ address.town_city }}",
                    county: "{{ address.county }}",
                    postcode: "{{ address.post_code }}",
                    country: "{{ address.country }}"
                });
            {% endfor %}

            // Populate address fields based on selected address
            function populateAddressFields(addressId) {
                const address = addresses.find(addr => addr.id == addressId);
                if (address) {
                    document.querySelector('#id_street_address1').value = address.street_address1 || '';
                    document.querySelector('#id_street_address2').value = address.street_address2 || '';
                    document.querySelector('#id_town_or_city').value = address.town_or_city || '';
                    document.querySelector('#id_county').value = address.county || '';
                    document.querySelector('#id_postcode').value = address.postcode || '';
                    document.querySelector('#id_country').value = address.country || '';
                } else {
                    // Clear fields if no valid address is found
                    document.querySelector('#id_street_address1').value = '';
                    document.querySelector('#id_street_address2').value = '';
                    document.querySelector('#id_town_or_city').value = '';
                    document.querySelector('#id_county').value = '';
                    document.querySelector('#id_postcode').value = '';
                    document.querySelector('#id_country').value = '';
                }
            }

            // Set up the event listener for the address_choices dropdown
            const addressSelect = document.querySelector('#id_address_choices');
            if (addressSelect) {
                addressSelect.addEventListener('change', function() {
                    const selectedAddressId = this.value;
                    populateAddressFields(selectedAddressId);
                });
            }
        });
    </script>

{% endblock %}