cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

fine_furnishings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profiles/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('products/', include('products.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('sofas/', views.sofa_products, name='sofa_products'),
    path('bedroom/', views.bedroom_products, name='bedroom_products'),
    path('dining/', views.dining_products, name='dining_products'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from profiles.models import UserProfile, UserAddress
from products.models import Product

# Create your models here.
class Order(models.Model):
    """
    A model representing a user's order
    """
    order_number = models.CharField(max_length=50, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, null=True, on_delete=models.SET_NULL, related_name='orders')
    address = models.ForeignKey(UserAddress, on_delete=models.PROTECT)
    product_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    delivery_charge = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=30)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    order_date = models.DateTimeField(auto_now_add=True)
    user_name = models.CharField(max_length=255, blank=True, null=True)
    user_email = models.EmailField(blank=True, null=True)
    user_phone = models.CharField(max_length=50, blank=True, null=True)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    class Meta:
        unique_together = ('user_profile', 'order_number')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()
    
    def update_order_total(self):
        """
        Update the order total each time a line item is added,
        including the delivery fee.
        """
        self.product_total = self.order_items.aggregate(Sum('order_items_total'))['order_items_total__sum'] or 0
        self.delivery_charge = settings.STANDARD_DELIVERY_FEE

        self.order_total = self.product_total + self.delivery_charge
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)


    def __str__(self):
        return f"Order Number: {self.order_number}"


class OrderItems(models.Model):
    """
    A model representing each item within an order
    """
    order = models.ForeignKey(Order, null=False, blank=False, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.PROTECT)
    bedframe_size = models.CharField(max_length=10, null=True, blank=True) # 3', 4', 4'6", 5', 6'
    quantity = models.IntegerField(null=False, blank=False, default=0)
    order_items_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    class Meta:
        unique_together = ('order', 'product')

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order items total
        and update the order total.
        """
        self.order_items_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Product ID: {self.product.product_id} on Order {self.order.order_number}"

products/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Create your models here.
class Category(models.Model):
    """
    Model representing product categories
    """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    Model representing individual product details
    """
    categories = models.ManyToManyField('Category')
    product_id = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    bedframe_sizes = models.BooleanField(default=False, null=True, blank=True)
    dimensions_height = models.CharField(max_length=100, default='0')
    dimensions_width = models.CharField(max_length=100, default='0')
    dimensions_depth = models.CharField(max_length=100, default='0')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
    
    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        category_names = [(c.id, c.name) for c in categories]

        self.fields['categories'].choices = category_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-secondary rounded-2'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Product, Category
from .forms import ProductForm

# The all_products view code was implemented with the help of the 
# Boutique Ado project walkthrough to implement the search bar's functionality
# and category filtering
def all_products(request):
    """ A view to render all products """

    products = Product.objects.all()
    query = None
    categories = None

    if request.GET:
        if 'categories' in request.GET:
            categories = request.GET['categories'].split(',')
            products = products.filter(categories__name__in=categories).distinct()
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter your search request.")
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query) | Q(categories__name__icontains=query)
            products = products.filter(queries).distinct()

            if not products.exists():
                messages.info(request, f'No products found for "{query}".')

    context = {
        'products': products,
        'search_term': query,
        'selected_categories': categories,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to render an individual product's details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


def sofa_products(request):
    """ A view to render the sofas category of products """

    products = Product.objects.filter(categories__name__iexact='sofa').distinct()
    context = {'products': products, 'category': 'Sofas'}
    return render(request, 'products/products.html', context)


def bedroom_products(request):
    """ A view to render the bedroom category of products """
    
    products = Product.objects.filter(categories__name__iexact='bedroom').distinct()
    context = {'products': products, 'category': 'Bedroom'}
    return render(request, 'products/products.html', context)


def dining_products(request):
    """ A view to render the dining category of products """
    
    products = Product.objects.filter(categories__name__iexact='dining').distinct()
    context = {'products': products, 'category': 'Dining'}
    return render(request, 'products/products.html', context)


# The product CRUD functionality (add, edit, delete) implemented for site admins was implemented
# with the help of the Boutique Ado Walkthrough - Product Admin

@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store administrators can add a product.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()
        
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store administrators can edit products.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing "{product.name}"')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store administrators can delete products.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f'"{product.name}" deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block meta_description %}Product Admin Page - allows authorized and logged in website administrators to add a new product.{% endblock %}

{% block search_bar %}
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}

    {% if not user.is_authenticated %}
        <script type="text/javascript">
            window.location.href =
            "{% url 'account_login' %}?next={% url 'checkout' %}";
        </script>
    {% else %}
        <div class="container text-white mb-3">
            <div class="row justify-content-center mt-md-3">
                <div class="col-md-8 col-sm-12 text-center">
                    <hr>
                    <h1 class="text-center text-white wishlist-text">Product Management</h1>
                    <h4 class="text-center text-white">Add Product</h4>
                    <hr>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 text-center">
                    <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <div class="text-right">
                            <a class="btn btn-outline-secondary text-white rounded-2" href="{% url 'products' %}">Cancel</a>
                            <button class="btn btn-secondary rounded-2" type="submit">Add Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
    {% endif %}
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block meta_description %}Product Admin Page - allows authorized and logged in website administrators to edit an existing product.{% endblock %}

{% block search_bar %}
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}

    {% if not user.is_authenticated %}
        <script type="text/javascript">
            window.location.href =
            "{% url 'account_login' %}?next={% url 'checkout' %}";
        </script>
    {% else %}
        <div class="container text-white mb-3">
            <div class="row justify-content-center mt-md-3">
                <div class="col-md-8 col-sm-12 text-center">
                    <hr>
                    <h1 class="text-center text-white wishlist-text">Product Management</h1>
                    <h4 class="text-center text-white">Edit Product</h4>
                    <hr>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 col-sm-12 text-center">
                    <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <div class="mt-3">
                            <span class="text-left mr-5">
                                <a type="button"
                                    class="btn btn-outline-danger mr-3"
                                    data-toggle="modal"
                                    data-target="#deleteProductModal">
                                        Delete Product
                                </a>
                            </span>
                            <span class="text-right ml-5">
                                <a class="btn btn-outline-secondary text-white rounded-2 ml-3" href="{% url 'products' %}">Cancel</a>
                                <button class="btn btn-secondary rounded-2" type="submit">Update Product</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
    {% endif %}

<!-- Delete Product Modal -->
<div class="modal fade" id="deleteProductModal" tabindex="-1" role="dialog"
aria-labelledby="deleteProductModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteProductModalLabel">
          Are you sure you want to delete this product?</h5>
          <button type="button" class="close" data-dismiss="modal"
          aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>
          This action cannot be undone.
          This product will be permanently deleted.
          </p>
        </div>
        <div class="modal-footer">
          <form method="post" action="{% url 'delete_product' product.id %}">
              {% csrf_token %}
              <button type="button" class="btn btn-secondary"
              data-dismiss="modal">
              Cancel
              </button>
              <button type="submit" class="btn btn-danger">
              Delete Product
              </button>
          </form>
        </div>
      </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block meta_description %}Find detailed information on each furniture product, including descriptions, prices and dimensions, on the product detail page of the Fine Furnishings website.{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}

    <div class="container products-container text-white pb-5">
        <div class="col-12 text-center">
            <h1 class="display-6">{{ product.name }}</h1>
        </div>
        <div class="row mt-4">
            <div class="col-lg-6 text-center">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img src="{{ product.image.url }}"
                    class="img-fluid product-page-img"
                    alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="url 'product_detail' product.id">
                    <img
                    src="{% static 'images/coming-soon-placeholder-image.png' %}"
                    class="img-fluid" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
            <div
            class="col-lg-6 d-flex flex-column pl-5 justify-content-center">
                <a href="{% url 'add_to_wishlist' product.id %}" class="mb-3">
                    <img src="{% static 'wishlist-heart.ico' %}"
                    alt="Wishlist Heart icon">
                </a>
                <div class="row mb-3">
                    <div class="col">
                        <h5>Price: €{{ product.price }}</h5>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <h5>Product ID: {{ product.product_id }}</h5>
                    </div>
                </div>
                <form action="{% url 'add_to_cart' product.id %}"
                method="POST" class="form">
                    {% csrf_token %}
                    {% with product.bedframe_sizes as s %}
                        {% if s %}
                            <div class="col-12 mb-3">
                                <p><strong>Size:</strong></p>
                                <select class="form-control rounded-0 w-50"
                                name="bedframe_size" id='id_bedframe_size'>
                                    <option value="3ft">3'</option>
                                    <option value="4ft">4'</option>
                                    <option value="4ft6in">4'6"</option>
                                    <option value="5ft">5'</option>
                                    <option value="6ft">6'</option>
                                </select>
                            </div>
                        {% endif %}
                    {% endwith %}
                    <div class="form-group">
                        <div class="row align-items-center">
                            <div class="col">
                                <h5>Quantity:</h5>
                            </div>
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button
                                        class=
                                        "decrement-qty btn btn-outline-secondary rounded-0"
                                        data-item_id="{{ product.id }}"
                                        id="decrement-qty_{{ product.id }}">
                                            <span>
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input type="number"
                                    name="quantity" value="1" min="1" max="50"
                                    class=
                                    "form-control quantity_input rounded-0 text-center w-auto"
                                    data-item_id="{{ product.id }}"
                                    id="id_quantity_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button
                                        class=
                                        "increment-qty btn btn-outline-secondary rounded-0"
                                        data-item_id="{{ product.id }}"
                                        id="increment-qty_{{ product.id }}">
                                            <span>
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="row">
                            <div class="col">
                                <input type="submit"
                                class="btn btn-secondary"
                                value="Add to Cart">
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="redirect_url"
                    value="{{ request.path }}">
                </form>
                {% if request.user.is_superuser %}
                    <div class="ml-5 pt-3 mt-3">
                        <a type="button"
                        class="btn btn-outline-secondary text-white"
                        href="{% url 'edit_product' product.id %}">
                            Edit Product
                        </a>
                        <a type="button"
                        class="btn btn-outline-danger"
                        data-toggle="modal"
                        data-target="#deleteProductModal">
                            Delete Product
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row mt-4 justify-content-center">
            <div class="col-12 text-center">
                <p class="lead">{{ product.description }}</p>
            </div>
        </div>
        <div class="row mt-4 text-center">
            <div class="col-sm-4">
                <h5>Height: {{ product.dimensions_height }}</h5>
            </div>
            <div class="col-sm-4">
                <h5>Width: {{ product.dimensions_width }}</h5>
            </div>
            <div class="col-sm-4">
                <h5>Depth: {{ product.dimensions_depth }}</h5>
            </div>
        </div>
    </div>

<!-- Delete Product Modal -->
<div class="modal fade" id="deleteProductModal" tabindex="-1" role="dialog"
aria-labelledby="deleteProductModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteProductModalLabel">
          Are you sure you want to delete this product?</h5>
          <button type="button" class="close" data-dismiss="modal"
          aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>
          This action cannot be undone.
          This product will be permanently deleted.
          </p>
        </div>
        <div class="modal-footer">
          <form method="post" action="{% url 'delete_product' product.id %}">
              {% csrf_token %}
              <button type="button" class="btn btn-secondary"
              data-dismiss="modal">
              Cancel
              </button>
              <button type="submit" class="btn btn-danger">
              Delete Product
              </button>
          </form>
      </div>
      </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block meta_description %}Explore the complete selection of premium furniture products available on the Fine Furnishings website. Visit our product page to find the ideal furnishings for your space.{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container products-container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4">
        {% for product in products %}
        <div class="col mb-4">
            <div class="card h-100">
                {% if product.image %}
                <a href="{% url 'product_detail' product.id %}">
                    <img src="{{ product.image.url }}"
                    class="card-img" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="{% url 'product_detail' product.id %}">
                    <img
                    src="{% static 'images/coming-soon-placeholder-image.png' %}"
                    class="card-img" alt="{{ product.name }}">
                </a>
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        {{ product.name }}
                        <a href="{% url 'add_to_wishlist' product.id %}">
                            <img src="{% static 'wishlist-heart.ico' %}"
                            alt="Wishlist Heart icon">
                        </a>
                    </h5>
                    <p class="card-text">Price: €{{ product.price }}</p>
                    <p class="card-text">{{ product.description }}</p>
                </div>
                {% if request.user.is_superuser %}
                    <small class="pb-3 text-center">
                        <a type="button"
                        class="btn btn-outline-secondary"
                        href="{% url 'edit_product' product.id %}">
                            Edit Product
                        </a>
                    </small>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}